defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

version: 2
jobs:
  build-job:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
  deploy-job:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Python
          command: sudo apt-get install python3 python-pip python-dev
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 jfront bucket
          command: aws s3 sync dist s3://jfront --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
